Changes made on 31-1-2020 for view, maintain and swagger
EC-Release/web-ui pull request #1
Opened 2020-01-31 18:22 UTC by Subhash-vishwakarma

2020-01-31 18:40 UTC, ayasuda2003 commented on README.md
> -[![Build Status](https://travis-ci.com/Enterprise-connect/web-ui-admin.svg?branch=v1.1beta)](https://travis-ci.com/Enterprise-connect/web-ui-admin)
Some lines in this README are removed. E.g. the build badge line#1 Please verify and avoid the removal. @Subhash-vishwakarma @iamkoushikpal-ge

2020-01-31 18:41 UTC, ayasuda2OO3 requested changes
Please verify my comments in the README

2020-02-01 03:38 UTC, Subhash-vishwakarma commented
updated the readme.md file as mentioned @ayasuda2003

2020-02-01 04:59 UTC, ayasuda2OO3 approved these changes

2020-02-01 05:00 UTC, merged